### PR TITLE
Added a few courses on Roadmap.md

### PR DESCRIPTION
**Pull request by pabs-lop**
Added matplotlib, pandas, numpy courses into python libraries section.  Moved Jose Portilla's course into a new category called "Data Science Bootcamps"  since it covers more than just the libraries.  

Also, update Roadmap.md included routes i.e. Analyst, DS, ML, DL, and DE to be completed later.

### CODE REVIEW

**Comment by vedanthv** [comment]
Hi. Thanks for the addition of the courses and restructuring. But over the last call we had a couple of days back, we decided to split the roadmap into three tracks: Data Analyst,Data Engineer and Data Scientist. It would be great if you can create a new folder for either Data Engineer or Data Scientist because I am working on the Data Analyst track.

**Comment by vedanthv** [comment]
Then we can discuss and make the necessary changes to the roadmap over the call on 25th. Thanks for your help!!

**Comment by pabs-lop** [comment]
Got it.  I didn't know about that since I missed the call.  That's good to know.  Thank you for keeping me on the loop.

**Comment by pabs-lop** [comment]
Make the appropriate changes to Get_started.md

**Pull request closed without merging**
